/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dmodena.view;

import com.dmodena.model.Impressora;
import javax.swing.JOptionPane;

/**
 *
 * @author dmodena
 */
public class Impressao extends javax.swing.JFrame {
    Impressora impressora;
    
    /**
     * Creates new form Impressao
     */
    public Impressao() {
        initComponents();
        escolherImpressoraA();
    }
    
    private void limparCampos() {
        tfTexto.setText("");
        tfContinuacao.setText("");
        tfQuantidadePaginas.setText("");
        tfPaginaInicial.setText("");
        tfPaginaFinal.setText("");
        lblResposta.setText("");
    }
    
    private void escolherImpressoraA() {
        rdImpressoraA.setSelected(true);
        tfTexto.setEnabled(true);
        tfContinuacao.setEnabled(false);
        tfQuantidadePaginas.setEnabled(false);
        tfPaginaInicial.setEnabled(false);
        tfPaginaFinal.setEnabled(false);        
        tfTexto.requestFocus();
    }
    
    private void escolherImpressoraB() {
        rdImpressoraB.setSelected(true);
        tfTexto.setEnabled(true);
        tfContinuacao.setEnabled(false);
        tfQuantidadePaginas.setEnabled(false);
        tfPaginaInicial.setEnabled(true);
        tfPaginaFinal.setEnabled(true);        
        tfTexto.requestFocus();
    }
    
    private void escolherImpressoraC() {
        rdImpressoraC.setSelected(true);
        tfTexto.setEnabled(true);
        tfContinuacao.setEnabled(true);
        tfQuantidadePaginas.setEnabled(true);
        tfPaginaInicial.setEnabled(false);
        tfPaginaFinal.setEnabled(false);        
        tfTexto.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupImpressora = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdImpressoraA = new javax.swing.JRadioButton();
        rdImpressoraB = new javax.swing.JRadioButton();
        rdImpressoraC = new javax.swing.JRadioButton();
        btnImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTexto = new javax.swing.JTextField();
        tfContinuacao = new javax.swing.JTextField();
        tfQuantidadePaginas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPaginaInicial = new javax.swing.JTextField();
        tfPaginaFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGroupImpressora.add(rdImpressoraA);
        rdImpressoraA.setText("Impressora A");
        rdImpressoraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdImpressoraAActionPerformed(evt);
            }
        });

        btnGroupImpressora.add(rdImpressoraB);
        rdImpressoraB.setText("Impressora B");
        rdImpressoraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdImpressoraBActionPerformed(evt);
            }
        });

        btnGroupImpressora.add(rdImpressoraC);
        rdImpressoraC.setText("Impressora C");
        rdImpressoraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdImpressoraCActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel1.setText("Texto");

        jLabel2.setText("Continuação");

        jLabel3.setText("Qtd. Páginas");

        jLabel4.setText("Página Inicial");

        jLabel5.setText("Página Final");

        jLabel6.setText("Resposta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdImpressoraB)
                                    .addComponent(rdImpressoraA))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfContinuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfPaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(tfPaginaFinal))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdImpressoraC)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQuantidadePaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResposta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdImpressoraA)
                    .addComponent(jLabel1)
                    .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdImpressoraB)
                    .addComponent(jLabel2)
                    .addComponent(tfContinuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfPaginaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdImpressoraC)
                    .addComponent(jLabel3)
                    .addComponent(tfQuantidadePaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblResposta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdImpressoraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdImpressoraAActionPerformed
        limparCampos();
        escolherImpressoraA();
    }//GEN-LAST:event_rdImpressoraAActionPerformed

    private void rdImpressoraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdImpressoraBActionPerformed
        limparCampos();
        escolherImpressoraB();
    }//GEN-LAST:event_rdImpressoraBActionPerformed

    private void rdImpressoraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdImpressoraCActionPerformed
        limparCampos();
        escolherImpressoraC();
    }//GEN-LAST:event_rdImpressoraCActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        impressora = new Impressora();
        boolean respostaImpressoraA;
        int respostaImpressoraB;
        int[] respostaImpressoraC;
        String resposta;
        
        if(rdImpressoraA.isSelected()) {
            if(tfTexto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Favor preencer todos os campos!");
            }
            else {
                respostaImpressoraA = impressora.imprimir(tfTexto.getText());
                resposta = String.valueOf(respostaImpressoraA);
                lblResposta.setText(resposta);                
            }            
        }
        else if(rdImpressoraB.isSelected()) {
            if(tfTexto.getText().isEmpty() || tfPaginaInicial.getText().isEmpty() || tfPaginaFinal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Favor preencer todos os campos!");
            }
            else {
                respostaImpressoraB = impressora.imprimir(tfTexto.getText(), Integer.parseInt(tfPaginaInicial.getText()), Integer.parseInt(tfPaginaFinal.getText()));
                resposta = String.valueOf(respostaImpressoraB);
                lblResposta.setText(resposta);                
            }            
        }
        else {
            if(tfTexto.getText().isEmpty() || tfContinuacao.getText().isEmpty() || tfQuantidadePaginas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Favor preencer todos os campos!");
            }
            else {
                respostaImpressoraC = impressora.imprimir(tfTexto.getText(), tfContinuacao.getText(), Integer.parseInt(tfQuantidadePaginas.getText()));
                resposta = String.valueOf(respostaImpressoraC[0]);
                lblResposta.setText(resposta);               
            }            
        }        
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impressao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupImpressora;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JRadioButton rdImpressoraA;
    private javax.swing.JRadioButton rdImpressoraB;
    private javax.swing.JRadioButton rdImpressoraC;
    private javax.swing.JTextField tfContinuacao;
    private javax.swing.JTextField tfPaginaFinal;
    private javax.swing.JTextField tfPaginaInicial;
    private javax.swing.JTextField tfQuantidadePaginas;
    private javax.swing.JTextField tfTexto;
    // End of variables declaration//GEN-END:variables
}
